[profile]
name=Rootz Corp
email=support@rootz.global

[ipfs]
url=https://rootz.digital/api/v0

; Chain used for wallets created by `epistery initialize` when it isn't given
; one. Change it with `epistery set-default-chain <chainId|name>`.
[default]
defaultChainId=137

[default.provider]
chainId=137
name=Polygon Mainnet
rpc=https://polygon-bor-rpc.publicnode.com
nativeCurrencyName=POL
nativeCurrencySymbol=POL
nativeCurrencyDecimals=18
